baseURL: https://nickchennn.netlify.app/
languageCode: en-us
title: Portfolio website for Nick Chen
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: More about me
    subtitle: |-
      Postgraduate student studying Masters in Analytics and Management at London Business School
    title: Welcome to Nick Chen's Personal Website
  blog: {}
  contact:
    address:
      - city: London, W2 1DB
        country: UK
        street: Edgware Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: crayonelephant2000@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (44)7555290466
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: LBS
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/NickChennn
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/nick-chen-504616184/
  image: ''
  name: Nick Chen
  navigation:
    button1:
      - name: Home
        url: '#'
 #   button2:
  #    - name: Log In
   #     url: '#'
    links:
  #    - name: Home
   #     url: '#'
      - name: Activities
        url: blogs
      - name: CV
        url: blogs/cv
      - name: Personal Life
        url: blogs/personal_life
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: LBS.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Excess rentals in Transport for London bike sharing
        url: blogs/assignment1
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: CV
        url: blogs/cv
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Assignment 2
        url: blogs/assignment2
    #  - image: pic04.jpg
     #   subtitle: Nisl Sed Aliquam
   #     title: Personal Life
    #    url: blogs/personal_life
    #  - image: pic05.jpg
     #   subtitle: Ipsum Dolor Sit Amet
     #   title: Consequat
     #   url: blogs/ipsum
   #   - image: pic06.jpg
     #   subtitle: Feugiat Amet Tempus
     #   title: Etiam
      #  url: blogs/ipsum
  two:
    buttonText: More about me
    enable: yes
    subtitle: "Thank you for spending time on knowing the academic side of me. Apart from being a financial enthusiast and a data analyst, I am also a person who enjoys every melody in my life."
    title: Personal Life
    url: blogs/personal_life
